name: Al_Arqam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  location: ^6.0.2
  bot_toast: ^4.1.3
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  devicelocale: ^0.8.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.15
  flutter_verification_code: ^1.1.7

  # ✅ مكتبات الموقع المحسنة (احذف location package القديم)
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  get_it: ^8.0.2
  google_maps_flutter: ^2.10.0
  hive_flutter: ^1.1.0
  http: ^1.2.2
  iconsax: ^0.0.8
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  percent_indicator: ^4.2.4
  rename: ^3.0.2


  # ✅ مكتبة الاستشعار للبوصلة
  sensors_plus: ^4.0.0

  timezone: ^0.9.2
  just_audio: ^0.9.46
  url_launcher: ^6.3.1
  vibration: ^3.1.3
  get: ^4.7.2

  # ❌ تم حذف location package لتجنب التعارض
  # location: ^8.0.0  # احذف هذا السطر

  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  lottie: ^3.3.1
  video_player: ^2.9.5
  flick_video_player: ^0.9.0
  intl_phone_field: ^3.2.0
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.14.3"
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.1
  flutter_test:
    sdk: flutter

# ✅ إعدادات الأيقونة المخصصة
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/arqam_logo.png"
  image_path_ios: "assets/images/arqam_logoapp.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/images/individual/

  fonts:
    - family: NotoKufiArabic
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf

    - family: KfgqpcHafsUthmanicScriptRegular
      fonts:
        - asset: assets/fonts/uthmani/KfgqpcHafsUthmanicScriptRegular-1jGEe.ttf
        - asset: assets/fonts/uthmani/KfgqpcHafsUthmanicScriptRegular-nARZ1.ttf

flutter_intl:
  enabled: true